//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCelerium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollationEntry
    {
        public int ID { get; set; }
        public string AgentID { get; set; }
        public string ConstituencyID { get; set; }
        public int PartyID { get; set; }
        public System.DateTime DateSend { get; set; }
        public int NumberOfVote { get; set; }
        public Nullable<int> PollingStationID { get; set; }
    }
}
