//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCelerium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Constituency
    {
        public Constituency()
        {
            this.Agents = new HashSet<Agent>();
            this.ElectoralAreas = new HashSet<ElectoralArea>();
        }
    
        public int ID { get; set; }
        public string ConstituencyName { get; set; }
        public string ConstituencyNo { get; set; }
        public int DistrictID { get; set; }
    
        public virtual ICollection<Agent> Agents { get; set; }
        public virtual District District { get; set; }
        public virtual ICollection<ElectoralArea> ElectoralAreas { get; set; }
    }
}
