//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCelerium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credit
    {
        public int ID { get; set; }
        public string ClientID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateDisbursed { get; set; }
        public string UserID { get; set; }
        public string ContractID { get; set; }
        public double Amount { get; set; }
        public System.DateTime DateFirstPyt { get; set; }
        public string TypeID { get; set; }
        public bool status { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
