//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCelerium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class District
    {
        public District()
        {
            this.Agents = new HashSet<Agent>();
            this.Constituencies = new HashSet<Constituency>();
        }
    
        public int ID { get; set; }
        public string DistrictName { get; set; }
        public int RegionID { get; set; }
    
        public virtual ICollection<Agent> Agents { get; set; }
        public virtual ICollection<Constituency> Constituencies { get; set; }
        public virtual Region Region { get; set; }
    }
}
