//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCelerium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Echeance
    {
        public Echeance()
        {
            this.CreditTypes = new HashSet<CreditType>();
        }
    
        public int EcheanceID { get; set; }
        public string EcheanceName { get; set; }
    
        public virtual ICollection<CreditType> CreditTypes { get; set; }
    }
}
