//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCelerium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectoralArea
    {
        public ElectoralArea()
        {
            this.PollingStations = new HashSet<PollingStation>();
        }
    
        public int ID { get; set; }
        public string ElectoralAreaName { get; set; }
        public int Constituency { get; set; }
    
        public virtual Constituency Constituency1 { get; set; }
        public virtual ICollection<PollingStation> PollingStations { get; set; }
    }
}
