//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCelerium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PollingStation
    {
        public PollingStation()
        {
            this.Agents = new HashSet<Agent>();
        }
    
        public int ID { get; set; }
        public string PollingStationNo { get; set; }
        public string PollingStationName { get; set; }
        public Nullable<int> RegisteredVoters { get; set; }
        public Nullable<int> TransferedAway { get; set; }
        public Nullable<int> Transfered_into { get; set; }
        public Nullable<int> ElectoralAreaID { get; set; }
    
        public virtual ICollection<Agent> Agents { get; set; }
        public virtual ElectoralArea ElectoralArea { get; set; }
    }
}
