//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCelerium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostedTansaction
    {
        public int PostingID { get; set; }
        public System.DateTime PostingStamp { get; set; }
        public string UserID { get; set; }
        public string AgentInfo { get; set; }
        public int Numtrans { get; set; }
        public decimal SPaiments { get; set; }
        public decimal SCollectes { get; set; }
        public decimal SPayable { get; set; }
        public decimal SNouveauClient { get; set; }
    }
}
