//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCelerium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public Region()
        {
            this.Agents = new HashSet<Agent>();
            this.Districts = new HashSet<District>();
        }
    
        public int ID { get; set; }
        public string RegionName { get; set; }
        public string Symbol { get; set; }
    
        public virtual ICollection<Agent> Agents { get; set; }
        public virtual ICollection<District> Districts { get; set; }
    }
}
