//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCelerium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminalAssigned
    {
        public int Id { get; set; }
        public int TerminalID { get; set; }
        public int AgentID { get; set; }
        public string UserID { get; set; }
        public System.DateTime DateAssigned { get; set; }
        public bool IsEnabled { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Commerciaux Commerciaux { get; set; }
        public virtual Terminal Terminal { get; set; }
    }
}
