//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCelerium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terminal
    {
        public Terminal()
        {
            this.TerminalAssigneds = new HashSet<TerminalAssigned>();
        }
    
        public int Id { get; set; }
        public string TerminalID { get; set; }
        public int Type { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string EMEI { get; set; }
    
        public virtual ICollection<TerminalAssigned> TerminalAssigneds { get; set; }
        public virtual TerminalType TerminalType { get; set; }
    }
}
