//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCelerium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vTransaction
    {
        public System.DateTime Date { get; set; }
        public string Nom_Commercial { get; set; }
        public string Nom_Client { get; set; }
        public double Solde_Ouverture { get; set; }
        public double Debit { get; set; }
        public double Credit { get; set; }
        public double Solde_Fermeture { get; set; }
        public int id { get; set; }
        public string AgentId { get; set; }
    }
}
